application: vinaymavi
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: index.html


  
- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /imageDesc.json
  script: imageDesc.json

- url: /views/main.html
  script: /views/main.html

- url: /fonts/glyphicons-halflings-regular.woff
  script: /fonts/glyphicons-halflings-regular.woff

- url: /fonts/glyphicons-halflings-regular.ttf
  script: /fonts/glyphicons-halflings-regular.ttf